let MAX_NOISE_SEED = 10000;

let MODULE_RADIUS;
let MODULE_VERTEX_COUNT = 6;

//let MODULE_RATIO_TO_CANVAS = 0.45;
let MODULE_RATIO_TO_CANVAS = 0.35;

let FPS_DEFAULT = 30;
let FPS_RELATIVE_SPEED;

let BLACK = 0;
let WHITE = 255;
